//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilerVehiculo_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int CodReserva { get; set; }
        public string CodVehiculo { get; set; }
        public string CodCliente { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> NroDias { get; set; }
        public Nullable<int> NroRetraso { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
